In [3]:
import pandas as pd
import os
import json

In [6]:
BASE_DIR = '../3d-object-detection-for-autonomous-vehicles/'

def check_file(file):
    file_path = os.path.join(BASE_DIR, 'train_data', f'{file}.json')

    with open(file_path, 'r') as f:
        data = json.load(f)
    df = pd.DataFrame(data)
    return df.head()

# Check attribute

In [8]:
check_file('attribute')

,description,token,name
0,,f5081f1e5aa941f9d9f727ad186c8db67b916336f975a2...,object_action_lane_change_right
1,,1b388c1f5e5149ae173ad3d674e7ad7f1847e213173d14...,object_action_running
2,,17d61007ee69782e0ad8ffa5f8cd4c075f18b4b09e11f0...,object_action_lane_change_left
3,,5466ded30df08d7d825412ac907017d6ae00ff19051c63...,object_action_parked
4,,8b08df37edc70b7327d54b3fbf9e7e5894e1a31a93fe77...,object_action_standing

# Check calibrated_sensor

In [9]:
check_file('calibrated_sensor')

,sensor_token,rotation,camera_intrinsic,translation,token
0,c84592e22beb2c0f14d5159245ce8d6678431b879e940e...,"[-0.6784803059109364, 0.6875255645268346, 0.19...","[[882.42699274, 0, 602.047851885], [0.0, 882.4...","[1.0399186259366102, 0.30857658859026604, 1.65...",80349b63ead8bfe5f4ce2cbe27fed9e4b5d699a5fc4222...
1,eb9e8f60a3d6e3328d7512b9f8e6800127fe91f4d62bc8...,"[0.5048435722738135, -0.4988633710749635, 0.49...","[[879.50613649, 0, 629.72481947], [0.0, 879.50...","[1.5315349031014653, -0.043313252718947544, 1....",72535fe1d2c8a1fc3f1e5d83c12b207a1c49aac349ee64...
2,f7dad6bb70cb8e6245f96e5537e382848335872e6e2592...,"[0.6837255817101214, -0.6842216370132779, 0.17...","[[881.904049355, 0, 616.93208239], [0.0, 881.9...","[1.275226285613853, 0.30645141315115104, 1.665...",ff2b3bd0f98a2e304c10cb979ff8f6c198efa631860848...
3,286718e1fbc8c8f0ca441969d91c36a8a809666e049e54...,"[0.5296938708729468, -0.4724561819772816, 0.46...","[[3421.14214546, 0, 1003.11947364], [0.0, 3421...","[1.5230760861194976, 0.033000106025969055, 1.6...",06e8407200e185f3b0efc2f09dfa13af10ec955e01ad5b...
4,f7dad6bb70cb8e6245f96e5537e382848335872e6e2592...,"[0.6850555759619519, -0.6810775131317202, 0.17...","[[876.90379026, 0, 602.677516295], [0.0, 876.9...","[1.3114424079053386, 0.35032961057556977, 1.62...",136ac6281dbfad1c2f03936f08737aaf6e1f6ae42eadf1...

# Check category

In [10]:
check_file('category')

,description,token,name
0,,8eccddb83fa7f8f992b2500f2ad658f65c9095588f3bc0...,car
1,,73e8de69959eb9f5b4cd2859e74bec4b5491417336cad6...,pedestrian
2,,f81f51e1897311b55c0c6247c3db825466733e08df687c...,animal
3,,a8619a81f5acc7da2a2f034420db2b2f43a015c8c68982...,other_vehicle
4,,7ea5868735dc408109bfa74fd139bd8c5aa3767b52e054...,bus

# Check ego_pose

In [11]:
check_file('ego_pose')

,rotation,translation,token,timestamp
0,"[0.8045437502844562, 0.02410792365998265, 0.01...","[622.726103039258, 3460.3733051620957, -6.8134...",2de7c52546f3f9bf6734084da8a2c1edaa0ffbea7f6e86...,1.547166e+15
1,"[-0.5929898606273702, -0.011481443936186955, 0...","[422.73128659665366, 2823.226294125566, -18.25...",b270648672b4995af5aa80e34c8150897b17c9b96dc6b8...,1.548697e+15
2,"[0.2796686043730183, 0.00271155518685425, 0.00...","[1112.137330836936, 1671.8727689601853, -24.53...",c85d360434ae69600fa5918da32375335b3b3571be7c2b...,1.549920e+15
3,"[0.9635040845956131, 0.008858425028518862, -0....","[1558.7315956474536, 1367.4379093573166, -21.4...",71ad25a1d764365b9f8a29c9067ad8dbd27e6e849becde...,1.557852e+15
4,"[0.962480110281498, 0.01607462664369117, -0.00...","[1840.7916379616522, 1198.6391492355403, -19.8...",9aa823e983e1131b3e8625bb7d80652863cec275efe82f...,1.548979e+15

# Check instance

In [12]:
check_file('instance')

,last_annotation_token,category_token,token,first_annotation_token,nbr_annotations
0,bcaa7c8be6503c2c2767b414e89598ea45ec1bf431eec1...,8eccddb83fa7f8f992b2500f2ad658f65c9095588f3bc0...,c50ef1538e11e03d232eca295c80b0e76040507d4d2785...,9811e373205791873b2a6aeb7852392fd4e060ea00074d...,49
1,239d0037b395a24dc110529cbd4be98595d12cea75b396...,8eccddb83fa7f8f992b2500f2ad658f65c9095588f3bc0...,a2629c325a79dce75fd81d84ef740f3ef2d5f1bce25e70...,8120e562b58cc2c7945b9490262f08b1645563565a4d61...,8
2,3c6fc88ad381df38877db77de1401d4cde2ac8ed1d8e88...,8eccddb83fa7f8f992b2500f2ad658f65c9095588f3bc0...,570abc2fb67078ced6e96f7575c426db9128c98f05d161...,4e1e519ff84e06e10a2e5432e7fa645271de29b9649e9f...,8
3,6a8ae9350f035f919c5ca2e56f5f5146bbf11fc7cd2e33...,8eccddb83fa7f8f992b2500f2ad658f65c9095588f3bc0...,13d1f3b371fee6e5d48caf485d6cd77ee596a74cb65c10...,b168495ce46746299d77892f89cdee90c9d60d6dec6ec5...,28
4,804c82796713e93b4d52f3aeffceafef11acd9df2e4183...,8eccddb83fa7f8f992b2500f2ad658f65c9095588f3bc0...,2d385a1fd60f20328382dd7484072712a4af3c34b3b2b1...,35564902196445be52d2b95aafa1e41c77505199ec732f...,39

# Check log

In [14]:
check_file('log')

,date_captured,location,token,vehicle,logfile
0,2019-05-14,Palo Alto,da4ed9e02f64c544f4f1f10c6738216dcb0e6b0d50952e...,a101,
1,2019-03-07,Palo Alto,0a6839d6ee6804113bb5591ed99cc70ad883d0cff396e3...,a006,
2,2019-03-06,Palo Alto,a939e6edc494777d058c3b1eafb91a7236f6b4ff5e98c9...,a011,
3,2019-03-06,Palo Alto,e8f8379c823fd0505b63f2612505e1d3de1018ecc3328f...,a012,
4,2019-05-02,Palo Alto,ccc0662a4dbc63f589358ac9589b677f6d4165a128af93...,a101,

# Check map

In [15]:
check_file('map')

,log_tokens,token,filename,category
0,[da4ed9e02f64c544f4f1f10c6738216dcb0e6b0d50952...,53992ee3023e5494b90c316c183be829,maps/map_raster_palo_alto.png,semantic_prior

# Check sample_annotation

In [16]:
check_file('sample_annotation')

,token,num_lidar_pts,size,sample_token,rotation,prev,translation,num_radar_pts,attribute_tokens,next,instance_token,visibility_token
0,92bff46db1dbfc9679edc8091770c4256ac3c027e9f0a9...,-1,"[2.064, 5.488, 2.053]",db8b47bd4ebdf3b3fb21598bb41bd8853d12f8d2ef25ce...,"[0.265491936795379, 0, 0, 0.964113080243515]",db2c5aea69d8be40a746c5f3df9366e030189b07647212...,"[2680.2830359778527, 698.1969292852777, -18.04...",0,[1ba8c9a8bda54423fa710b0af1441d849ecca8ed7b7f9...,33e07b849d62718279c9548fe662d32247e319f0451cd4...,abea2eb040d9c8fa1a44fa54020daaf9e2aa696e95e1d2...,
1,04c4c9883de582c5c4e7a45273a978a52b0432de18883f...,-1,"[1.635, 4.339, 1.515]",edf37c1fb1024ba0c1f53ebbf10b6797f781199a9f0e4e...,"[-0.9603683930256266, 0, 0, 0.2787338330331926]",fadeb42661a9af6ff36d3ee60bb68b01a03c59e83bdcdc...,"[1208.642684768659, 1585.1812946970927, -23.56...",0,[7fc1ca3d36808cd1858e9c01ad4e7630ff3ca9e720065...,1b29baa915a0e1835b322e83efe0cfaa9b483fa96e1b34...,c3824f5ed11d382a4742d00a3a2e8deea4e6c21198151c...,
2,4226ce1636193ced735e21ff3c6dcc292415c72d0f84b4...,-1,"[1.963, 4.345, 1.749]",1841b7895e7163a2c1be87e8c1740e759a910cd59157b8...,"[-0.5869061410650688, 0, 0, 0.8096549768760207]",bdcef23d3174acfd0383b2b8faba5b9e77ddbc2b7b6160...,"[848.9346793681768, 2587.2870557176507, -20.15...",0,[1ba8c9a8bda54423fa710b0af1441d849ecca8ed7b7f9...,ada6f7609e72098e2838ba44b03a4f15c2441e19e0c560...,0e6f00583ee6a407f7f48b52b60d3a6539caa7fdbab17c...,
3,f2446d4ca4b3e79e982cf0a4134af12e71e7b59df42f42...,-1,"[2.2, 5.39, 2.187]",a970c764e7abd7ebc2cc4599a6e3ae58c9773ea3c9cf1d...,"[0.2735976366273557, 0, 0, 0.9618442354310418]",d24fee88f5367f04f721041737dbcc497a3a3e4f9bc443...,"[1994.4320280494098, 1128.30164336183, -18.054...",0,[7fc1ca3d36808cd1858e9c01ad4e7630ff3ca9e720065...,de973be82ff2cc335bddcf27635c5d9e322a468a0d8dbd...,da82552a3b59ecd73d3c0be8aecec67296585f5c4b473e...,
4,1f5bdec4a1dff45dbbb4db094445dd4051eb39c9b4a2a3...,-1,"[1.837, 5.406, 1.721]",b909de93ba19460eeea58074ccc1ef6bb302435f37b48c...,"[0.12864510419303685, 0, 0, 0.991690696319756]",ed091f417281204c1dc2f08b497e6e013280be43373dc4...,"[1030.3877156973385, 1667.13131694941, -23.764...",0,[5466ded30df08d7d825412ac907017d6ae00ff19051c6...,5e189a3afd1a723013a90e547991204ea14220ce0912f0...,21919dfc393baac38a32abe7acc09fd0e1f6f6020dcf9b...,

# Check sample_data

In [17]:
check_file('sample_data')

,is_key_frame,prev,fileformat,token,timestamp,next,ego_pose_token,sample_token,filename,calibrated_sensor_token,width,height
0,True,d190078ec7869ad5c9e5417371aa3b45eb1c22804a0a29...,bin,ad87e1763749cc8562cca68e2046db128185c80c3e7599...,1.549921e+15,8182fb6868baf63c245a4994b7f3034a7d281d1928a784...,d90d278f2084ae64c98b0aa2dd8d4f83c023f1313beeae...,fd5f1c634b59e3b4e0f7a5c48c768a7d334a63221fced3...,lidar/host-a007_lidar1_1233956183701948366.bin,3b463530b5bae9698c9cc803c1731c36abd359a7296e23...,NaN,NaN
1,True,83f6f61cb6f2fc9b985cc23bd5613219eee7da390cd083...,bin,ea079138d89f3887b2bfcddfe16b747e2ec7a366ce66b3...,1.551742e+15,c291c5e9c1c70363496e304e964a33036cace6d14c177e...,97c348ec54ca0cfc892361595513d34d19e53583f97832...,c60dc70e93949cbefdda68813cf024fe8e9103bc8a68d6...,lidar/host-a008_lidar1_1235777221601281486.bin,2dba2d3171d7c60b847d65d96babfd7efb487428fa5a3c...,NaN,NaN
2,True,44555daed204fea486ec10ea1747432501b9f06fe93041...,jpeg,454c65ee6c297d64b17852b4c56def9781a84dcb8558a8...,1.550705e+15,d4b751751ca5424375d0faf3d22b9af83e7c84e1598ba0...,dce9c81e168db4f6fa442cc0bd484a4926dfe73946ba59...,254cea140f7d14fc86e73f789794fb73f81c05831d40f3...,images/host-a007_cam6_1234740264650905006.jpeg,30fcfa36375c0d36fce508cd04c9b1dd07ac283eb87352...,2048.0,864.0
3,True,de75f3f347742035f2442f4a5fa0334946642daa2d07d8...,jpeg,779018e1f92debcf5c5c28e9577677c6595679780bdf9b...,1.546901e+15,4796998aae092f295fe4f96ce57fc673e3292c7b0368ac...,bb93bbeb3b6d151c805729dba52d4c0c0070f20376090b...,810503d8ca51e9692021ecb56e2b2f2098beaf396cd207...,images/host-a007_cam3_1230936242299360006.jpeg,76e7bb72dd96cb18f5c75abae3b5bab5e41bd4aac39445...,1224.0,1024.0
4,True,a208568472ef6719faa2540622ada30b004583de9153f4...,jpeg,d966960819eb0aca2883cd3c8d8c5e2540bda952a8cada...,1.549650e+15,1a82a24dafde93234579ae59f48498a8436361cc641a64...,53f6821330f6bc07603db70fde1a96b25bd919471e923c...,119b8c4bbaf1493bebaaa7d823934a8a3f5a80fb095630...,images/host-a004_cam2_1233685223917652006.jpeg,aac6241dd5e28264de261422696af2037868c5133d9329...,1224.0,1024.0

# Check sample

In [18]:
check_file('sample')

,next,prev,token,timestamp,scene_token
0,1d2350b3b20e3a5db2407e4075fc14f9f9ddfe0018f1da...,14511199ea101b40683cefafb9fcf5c2fb512fa500c3e6...,b98a05255ba2632e957884758cb31f0e6fcc8d3cd6ee76...,1.552084e+15,18c6c670114eebd813ef240b05b988646bbccbbc5254df...
1,4f027d171715d57cd62079924e439f9ab17d228f27999a...,692caabc1f06aeda9f43d6252a070178430dec2158f19e...,78ce15b2b7360b8cd696d1097c60ec2184b69c17412564...,1.557855e+15,8bc90aa0c14148c86d18c59cbe706a437d0710ed2dfb5e...
2,b66fb3c9a787cae35330b69f06cc18a7f06d0e61c7d06f...,0999dad89d3c95dd2976b4631b6deb3b3000e4de27afa3...,095d5bb88eb9cdd223b90d2a1475c0cf2f4b4c2a8aca82...,1.548780e+15,328ee9d180f02a82516e8c5b4113ed18d8a36d2023c3ed...
3,063ea8386aa8156c1cd7c91bb1ac433f0b58d471e12658...,3222c742893edd007b982e9e7db40b7a598972d07bf759...,c2f0b2b2c0d576d42eab6e8703c4eacd302a79d4d702bd...,1.549481e+15,3000622b0d524cddccec8df22e1613a9d821b26662a6f1...
4,163666a4128b13159abd8ba202d9f0b05229507c27fc6b...,,f59c9f22016b783c6a7e5225fc56fccaf4fe3df4a9d96c...,1.548802e+15,b8492fd868445918e25be1f061e5c3488252b8c05a6775...

# Check Scene

In [7]:
check_file('scene')

,log_token,first_sample_token,name,description,last_sample_token,nbr_samples,token
0,da4ed9e02f64c544f4f1f10c6738216dcb0e6b0d50952e...,24b0962e44420e6322de3f25d9e4e5cc3c7a348ec00bfa...,host-a101-lidar0-1241893239199111666-124189326...,,2346756c83f6ae8c4d1adec62b4d0d31b62116d2e1819e...,126,da4ed9e02f64c544f4f1f10c6738216dcb0e6b0d50952e...
1,0a6839d6ee6804113bb5591ed99cc70ad883d0cff396e3...,3b30673b9d944ec6058ef5a8debb4c0a6fe075bca7076e...,host-a006-lidar0-1236037883198113706-123603790...,,5ec01e4634ca91751311eaafb45a9196ba8616bf05edc8...,126,0a6839d6ee6804113bb5591ed99cc70ad883d0cff396e3...
2,a939e6edc494777d058c3b1eafb91a7236f6b4ff5e98c9...,fcad797faa988f50be306e5fb6971de295602ee9116bd9...,host-a011-lidar0-1235950297199142196-123595032...,,92690bc3dc7c90bd831146f8505c3b4b67603997d9df74...,126,a939e6edc494777d058c3b1eafb91a7236f6b4ff5e98c9...
3,e8f8379c823fd0505b63f2612505e1d3de1018ecc3328f...,8e1f13379721c1ab1d073607534ce7c195143cb8911715...,host-a012-lidar0-1235937130198577346-123593715...,,c9a3c20169f5ec811a81c3d12d55495ae4dc9b6f77403c...,126,e8f8379c823fd0505b63f2612505e1d3de1018ecc3328f...
4,ccc0662a4dbc63f589358ac9589b677f6d4165a128af93...,b6380a94d11315d22fd2313ae2e627ccb3579150cc9c67...,host-a101-lidar0-1240875136198305786-124087516...,,bb4297a8c979ee45eb8f33d682767347c385b6ed1dee2e...,126,ccc0662a4dbc63f589358ac9589b677f6d4165a128af93...

# Check sensor

In [19]:
check_file('sensor')

,modality,channel,token
0,camera,CAM_FRONT_LEFT,f7dad6bb70cb8e6245f96e5537e382848335872e6e2592...
1,lidar,LIDAR_FRONT_LEFT,629da739ea3a0814b9d79ffc3b99cdbc8bdbb6f97abf13...
2,camera,CAM_FRONT,eb9e8f60a3d6e3328d7512b9f8e6800127fe91f4d62bc8...
3,lidar,LIDAR_TOP,25bf751d7e35f295393d8a418731474b21c1f702e878c4...
4,camera,CAM_BACK_LEFT,c84592e22beb2c0f14d5159245ce8d6678431b879e940e...

# Check visibility

In [20]:
check_file('visibility')

     level                                        description token
0   v60-80   visibility of whole object is between 60 and 80%     3
1    v0-40    visibility of whole object is between 0 and 40%     1
2   v40-60   visibility of whole object is between 40 and 60%     2
3  v80-100  visibility of whole object is between 80 and 100%     4